theme: jekyll-theme-cayman
title: GeoContext
description: <img src="GeoContext_transparent.png" alt="geocontext logo" width="150"/> A social and political context for geoscience education
avatar: GeoContext_transparent.png
